### ISSUE TITLE
config.xml version problem

### ISSUE THREAD

**Issue by prjemian** [prjemian/pvWebMonitor#16]
when I try to start pvWebMonitor in sector1, on w.s. "vivaldi", logged in as "s1id", I get the following:

```
vivaldi > /APSshare/anaconda/x86_64/bin/python /APSshare/anaconda/x86_64/bin/pvWebMonitor /home/beams/S1ID/pvWebMon/config.xml
Traceback (most recent call last):
  File "/APSshare/anaconda/x86_64/bin/pvWebMonitor", line 9, in <module>
    load_entry_point('pvWebMonitor==2016.427.1', 'console_scripts', 'pvWebMonitor')()
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/main.py", line 97, in main
    configuration = read_config.read_xml(user_args.xml_config_file)
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/read_config.py", line 46, in read_xml
    utils.validate(tree, XML_SCHEMA_FILE)
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/utils.py", line 97, in validate
    return xsd.assertValid(xml_tree)
  File "src/lxml/lxml.etree.pyx", line 3491, in lxml.etree._Validator.assertValid (src/lxml/lxml.etree.c:182098)
lxml.etree.DocumentInvalid: Element 'pvWebMonitor__config', attribute 'version': [facet 'enumeration'] The value '1.0' is not an element of the set {'1.0.1'}., line 2
vivaldi >
```

**Comment by prjemian** [comment]
There is a recent upgrade to the pvWebMonitor application that allows you control of the additional files to be uploaded from the project directory to the web directory.  That compelled a change in the version number of the config.xml file (from 1.0 to 1.0.1).

To update your config.xml file to the new version, look at this page:
https://github.com/prjemian/pvWebMonitor/blob/master/src/pvWebMonitor/project/config.xml

line 2: that's the new version number to use
lines 28-35: those are the default file patterns to be copied

These patterns are used to identify the list of files copied from the project directory to the web directory, even if pvWebMonitor did not create them.  In the old version, they were preset internally.  The new version allows the user control over this list.

Make these changes, then restart pvWebMonitor and "it should just work."

**Comment by prjemian** [comment]
Internal to the program, I need to be able to start pvWebMonitor with the v1.0 config.xml file.  Worked on that a little but it did not get completed.
