### ISSUE TITLE
check XSLT files for syntax errors

### ISSUE THREAD

**Issue by prjemian** [prjemian/pvWebMonitor#18]
the exception trace presented when an XSLT fails is not very helpful

better to check the XML syntax first (xmllint --noout html_screen.xsl) and report any errors

**Comment by prjemian** [comment]
example:

```
INFO:root:(26177,pvWebMonitor,2016-09-06 11:21:31.290134) checkpoint, 3328 EPICS monitor events received
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.371786) problem with report():
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.379743)       Traceback (most recent call last):
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.379887)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 97, in start
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.379997)       try: self.report()                   # write contents of pvdb to a file
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380095)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 305, in report
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380192)       _xslt_(xslt_file_name, report_xml_file_name)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380295)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 45, in _xslt_
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380390)       utils.xslt_transformation(xslt_file, source_xml_file, output_xml_file)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380486)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/utils.py", line 120, in xslt_transformation
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380582)       src_doc = etree.parse(src_xml_file)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380682)         File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79801)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380778)         File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:115995)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380876)         File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116345)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.380979)         File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115233)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.381076)         File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:109930)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.381170)         File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.381265)         File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.381361)         File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:103967)
INFO:root:(26177,pvWebMonitor,2016-09-06 11:22:13.381456)       XMLSyntaxError: Document is empty, line 1, column 1
```

**Comment by prjemian** [comment]
another example:

```
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.294535) problem with report():
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298357)       Traceback (most recent call last):
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298473)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 97, in start
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298581)       try: self.report()                   # write contents of pvdb to a file
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298679)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 305, in report
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298775)       _xslt_(xslt_file_name, report_xml_file_name)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298871)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 45, in _xslt_
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.298974)       utils.xslt_transformation(xslt_file, source_xml_file, output_xml_file)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299071)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/utils.py", line 121, in xslt_transformation
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299167)       xslt_doc = etree.parse(xslt_file)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299271)         File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79801)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299373)         File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:115995)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299469)         File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116345)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299565)         File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115233)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299661)         File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:109930)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299756)         File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299852)         File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.299956)         File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:103967)
INFO:root:(23427,pvWebMonitor,2016-09-02 10:50:50.300052)       XMLSyntaxError: Opening and ending tag mismatch: table line 339 and body, line 432, column 20
```

**Comment by prjemian** [comment]
another example:

```
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.140682) problem with report():
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144036)       Traceback (most recent call last):
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144150)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 97, in start
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144238)       try: self.report()                   # write contents of pvdb to a file
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144323)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 298, in report
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144406)       _xslt_(xslt_file_name, report_xml_file_name)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144489)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 45, in _xslt_
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144611)       utils.xslt_transformation(xslt_file, source_xml_file, output_xml_file)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144697)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/utils.py", line 120, in xslt_transformation
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144781)       src_doc = etree.parse(src_xml_file)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144863)         File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79801)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.144986)         File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:115995)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145071)         File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116345)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145153)         File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115233)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145234)         File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:109930)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145324)         File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145406)         File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145487)         File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:103967)
INFO:root:(23427,pvWebMonitor,2016-09-02 12:24:28.145569)       XMLSyntaxError: Extra content at the end of the document, line 1447, column 1
```

**Comment by prjemian** [comment]
another example:

```
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.162613) problem with report():
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166050)       Traceback (most recent call last):
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166161)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 97, in start
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166261)       try: self.report()                   # write contents of pvdb to a file
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166357)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 287, in report
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166453)       _xslt_(xslt_file_name, pvlist_xml_file_name)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166549)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/pvwatch.py", line 45, in _xslt_
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166643)       utils.xslt_transformation(xslt_file, source_xml_file, output_xml_file)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166739)         File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/pvWebMonitor/utils.py", line 120, in xslt_transformation
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166859)       src_doc = etree.parse(src_xml_file)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.166955)         File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79801)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167048)         File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:115995)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167131)         File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116345)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167222)         File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115233)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167304)         File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:109930)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167385)         File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103404)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167467)         File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105058)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167548)         File "src/lxml/parser.pxi", line 611, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:103924)
INFO:root:(19741,pvWebMonitor,2016-08-31 15:55:24.167629)       IOError: Error reading file 'pvlist.xml': failed to load external entity "pvlist.xml"
```

**Comment by prjemian** [comment]
Confirmed that 68f6220 has resolved the problems observed with exception reporting

note: xmllint is not easily available
